#!/usr/bin/env node
const gitDateExtractor = require('git-date-extractor')
gitDateExtractor.getStamps({
    outputToFile: true,
    projectRootPath: `${__dirname}/../content/blog`,
    gitCommitHook: 'pre'
})